[project]
name = "evm-cfg-py"
version = "0.1.0"
description = "Creating Control Flow Graph (CFG) for Ethereum Smart Contract and Transaction execution path"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
